apiVersion: scheduling.k8s.io/v1
kind: PriorityClass

metadata:
  name: high-priority
value: 10000
globalDefault: false
description: "Pods with this priority class will be the least likely to be evicted and rescheduled during a scale event."
