apiVersion: extensions/v1beta1
kind: PodSecurityPolicy

metadata:
  name: privileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: "*"

spec:
  privileged: true
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  allowedCapabilities:
    - "*"

  volumes:
    - "*"

  hostNetwork: true
  hostIPC: true
  hostPID: true

  hostPorts:
    - min: 0
      max: 65535

  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny

  seLinux:
    rule: RunAsAny
