image:
  name: alpine/helm
  entrypoint: ["/bin/sh", "-c"]

before_script:
  - apk add --no-cache --update bash

stages:
  - deploy

pages:
  stage: deploy
  script:
    - ./publish.sh
    - mv artifacts/pages public
  artifacts:
    paths:
      - public
  only:
    - master
