apiVersion: v1
appVersion: 1.15.3
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- http://github.com/istio/cni
version: 1.15.3
