apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: global:secrets-editor
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.org.io/aggregate-to-secrets-admin: "true"

aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.org.io/aggregate-to-secrets-editor: "true"

rules:
  - apiGroups:
      - ""
    resources:
      - Secret
    verbs:
      - create
      - patch
      - update

  - apiGroups:
      - bitnami.com
    resources:
      - SealedSecret
    verbs:
      - create
      - patch
      - update
