apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: global:secrets-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"

aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.org.io/aggregate-to-secrets-admin: "true"

rules:
  - apiGroups:
      - ""
    resources:
      - Secret
    verbs:
      - delete
      - deletecollection

  - apiGroups:
      - bitnami.com
    resources:
      - SealedSecret
    verbs:
      - delete
      - deletecollection
