nameOverride: "helm"
fullnameOverride: "helm"

image:
  repository: docker.io/fluxcd/helm-operator
  tag: 1.0.0-rc3

createCRD: false
updateChartDeps: true

logFormat: fmt
logReleaseDiffs: true

chartsSyncInterval: 3m

configureRepositories:
  enable: true
  volumeName: repositories-yaml
  secretName: flux-helm-repositories
  cacheVolumeName: repositories-cache

rbac:
  create: true
  pspEnabled: true

serviceAccount:
  create: true
  name: helm

clusterRole:
  create: true
  name: helm

prometheus:
  enabled: true

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpression:
            - key: pool
              operator: In
              values:
                - system
