name: release

on:
  push:
    branches:
      - master
      - release/*
      - next

jobs:
  version:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: configure-git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: publish-charts
        uses: helm/chart-releaser-action@v1.0.0-rc.1
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: install-node
        uses: actions/setup-node@master

      - name: semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
